{% set name = "dakota" %}
{% set version = "6.9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://dakota.sandia.gov/sites/default/files/distributions/public/{{ name }}-{{ version }}-release-public.src.tar.gz
  md5: b2ce64fb8e93ea6db455f88b106d5f2b
  patches:
    - include-cmath.patch

build:
  number: 1

requirements:
  build:
    - cmake
    - {{ compiler('c') }}        # [linux]
    - {{ compiler('cxx') }}      # [linux]
    - {{ compiler('fortran') }}  # [linux]
    - gcc                        # [osx]
    - boost                      # [linux]
    - boost-gcc                  # [osx]
    - blas
    - lapack
    - perl
    - openmpi
    - python
  run:
    - libgcc                     # [osx]
    - boost                      # [linux]
    - boost-gcc                  # [osx]
    - blas
    - lapack
    - perl
    - openmpi

test:
  requires:
    - git
    - python

about:
  home: http://dakota.sandia.gov
  license: LGPL-2.1
  summary:
    The Dakota toolkit provides a flexible, extensible interface
    between simulation codes and a variety of iterative systems
    analysis methods, including optimization, uncertainty
    quantification, deterministic/stochastic calibration, and
    parametric/sensitivity/variance analysis.
