{% set name = "dakota" %}
{% set version = "6.9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://dakota.sandia.gov/sites/default/files/distributions/public/{{ name }}-{{ version }}-release-public.src.tar.gz
  md5: b2ce64fb8e93ea6db455f88b106d5f2b
  patches:
    - include-cmath.patch

build:
  number: 0

requirements:
  build:
    - cmake=3.3
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - boost=1.67
    - blas
    - lapack
    - perl
    - openmpi
    - python
  run:
    - libgcc-ng
    - libgfortran-ng
    - libstdcxx-ng

test:
  commands:
    - dakota --version

about:
  home: http://dakota.sandia.gov
  license: LGPL-2.1
  summary:
    The Dakota toolkit provides a flexible, extensible interface
    between simulation codes and a variety of iterative systems
    analysis methods, including optimization, uncertainty
    quantification, deterministic/stochastic calibration, and
    parametric/sensitivity/variance analysis.
  dev_url: http://dakota.sandia.gov
